# Generated by Django 4.1.3 on 2022-11-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_post_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
