# Generated by Django 4.1.3 on 2022-11-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_cat_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extendedinfo',
            field=models.TextField(default=True),
        ),
    ]
