# Generated by Django 4.1.3 on 2022-11-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_extendedinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterField(
            model_name='post',
            name='extendedinfo',
            field=models.TextField(),
        ),
    ]
