# Generated by Django 4.1.3 on 2022-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_home_alter_post_extendedinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('extendedinfo', models.TextField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
