# Generated by Django 4.1.3 on 2022-11-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_title_home_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
