# Generated by Django 4.1.3 on 2022-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_home_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
