# Generated by Django 4.1.3 on 2022-12-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_home_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='age',
            field=models.IntegerField(),
        ),
    ]
