# Generated by Django 4.1.3 on 2022-12-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_home_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='age',
            field=models.TextField(default=''),
        ),
    ]
