# Generated by Django 4.1.3 on 2022-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_agelived_home_lived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='lived',
            field=models.TextField(default=''),
        ),
    ]
