# Generated by Django 4.1.3 on 2022-12-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_home_lived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='lived',
        ),
    ]
