# Generated by Django 4.1.3 on 2022-12-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_home_lived'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Yearsold',
            field=models.IntegerField(null=True),
        ),
    ]
