# Generated by Django 4.1.3 on 2022-12-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_home_yearsold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='Yearsold',
        ),
    ]
