# Generated by Django 4.1.3 on 2022-12-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_home_yearsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='yearold',
            field=models.TextField(default=''),
        ),
    ]
