# Generated by Django 4.1.3 on 2022-12-03 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_home_yearold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='yearold',
        ),
    ]
