# Generated by Django 4.1.3 on 2022-12-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_home_yearold'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
