# Generated by Django 4.1.3 on 2022-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_home_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='birthday',
            field=models.TextField(default='xx.xx.xx'),
        ),
    ]
