# Generated by Django 4.1.3 on 2022-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_home_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
