# Generated by Django 4.1.3 on 2022-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='include', to='blog.exp'),
        ),
    ]
