# Generated by Django 4.1.3 on 2022-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_home_connection_delete_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='connection',
            field=models.ManyToManyField(blank=True, to='blog.exp'),
        ),
    ]
