# Generated by Django 4.1.3 on 2022-12-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_remove_home_connection_delete_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='status',
            new_name='telephonenumber',
        ),
        migrations.RemoveField(
            model_name='home',
            name='age',
        ),
        migrations.RemoveField(
            model_name='home',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='home',
            name='experience',
        ),
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='home',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
    ]
