# Generated by Django 4.1.3 on 2022-12-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_rename_status_home_telephonenumber_remove_home_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='telephonenumber',
            field=models.CharField(max_length=100),
        ),
    ]
