# Generated by Django 4.1.3 on 2022-12-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_home_telephonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(default='Малдыбаева 34б  ', max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(default='No data'),
        ),
        migrations.AlterField(
            model_name='home',
            name='telephonenumber',
            field=models.CharField(default='(+996)-123-456-789', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
