# Generated by Django 4.1.3 on 2022-12-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_category_alter_home_address_alter_home_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
