# Generated by Django 4.1.3 on 2022-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(default='Maldybaeva 34b  ', max_length=20),
        ),
    ]
