# Generated by Django 4.1.3 on 2022-12-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_home_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.URLField(max_length=100)),
                ('Addressurl', models.CharField(max_length=100)),
            ],
        ),
    ]
