# Generated by Django 4.1.3 on 2022-12-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularteachers',
            name='email',
            field=models.EmailField(default='', max_length=20),
        ),
    ]
