# Generated by Django 4.1.3 on 2022-12-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInfo', '0002_alter_popularteachers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(default='', max_length=20)),
                ('whatsapp', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
    ]
