# Generated by Django 4.1.3 on 2022-12-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInfo', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField(default=0, max_length=100)),
                ('graduates', models.IntegerField(default=0, max_length=100)),
                ('employees', models.IntegerField(default=0, max_length=100)),
                ('meetings', models.IntegerField(default=0, max_length=100)),
            ],
        ),
    ]
