# Generated by Django 4.1.3 on 2022-12-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInfo', '0005_stats_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='popularteachers',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
