# Generated by Django 4.1.3 on 2022-12-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInfo', '0006_alter_contacts_email_alter_popularteachers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularteachers',
            name='instagram',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
        migrations.AddField(
            model_name='popularteachers',
            name='telegram',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
        migrations.AddField(
            model_name='popularteachers',
            name='whatsapp',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
    ]
