# Generated by Django 4.1.3 on 2022-12-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInfo', '0008_aboutinai'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinai',
            name='quote',
            field=models.TextField(default='Start something that matters'),
        ),
    ]
