# Generated by Django 4.1.3 on 2022-12-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_experience_vacancy_salary_vacancy_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(default='No data')),
                ('email', models.EmailField(default='', max_length=20)),
            ],
        ),
    ]
