# Generated by Django 4.1.3 on 2022-12-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_popularteachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularTeachers',
        ),
    ]
