# Generated by Django 4.1.3 on 2022-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_delete_popularteachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='Megacom',
            field=models.CharField(default='Введите номер', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='Oshka',
            field=models.CharField(default='Введите номер', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='telegram',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='whatsapp',
            field=models.CharField(default='Введите ссылку', max_length=100),
        ),
    ]
