# Generated by Django 4.1.3 on 2022-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_megacom_vacancy_oshka_vacancy_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='Megacom',
            field=models.CharField(default='+(996) 555 881 353', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Oshka',
            field=models.CharField(default='+(996) 755 881 353', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='email',
            field=models.EmailField(default='polotov.arlen@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='telegram',
            field=models.CharField(default='https://t.me/huriskop', max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='whatsapp',
            field=models.CharField(default='https://wa.me/996703372542', max_length=100),
        ),
    ]
