# Generated by Django 4.1.3 on 2022-12-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_description_alter_vacancy_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='S', max_length=100),
        ),
    ]
